# Generated by Django 3.1 on 2020-09-06 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Образование'), (2, 'Наука'), (3, 'Здравоохранение'), (4, 'Нефтехимическая промышленность'), (5, 'Промышленность'), (6, 'Легкая промышленность'), (7, 'Пищевая промышленность'), (8, 'Траснпорт и коммуникации'), (9, 'Лесное хозяйство'), (10, 'Сельское хозяйство'), (11, 'Архитектура и строительство'), (12, 'Энергетика'), (13, 'Связь и информатизация'), (14, 'Природные ресурсы и охрана окружающей среды')], max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отрасль/функциональная сфера',
                'verbose_name_plural': 'Отрасли/функциональные сферы',
            },
        ),
    ]
