# Generated by Django 3.1 on 2020-10-09 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_auto_20201009_2038'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Отрасль')),
                ('degree', models.ManyToManyField(to='indicators.Degree')),
            ],
            options={
                'verbose_name': 'Отрасль/функциональная сфера',
                'verbose_name_plural': 'Отрасли/функциональные сферы',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.industry', verbose_name='Отрасль'),
        ),
    ]
