# Generated by Django 3.1 on 2020-10-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201009_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='degree',
        ),
    ]
