# Generated by Django 3.1 on 2020-08-17 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование показателя - степень')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('applying', models.BooleanField(blank=True, default=False, null=True, verbose_name='Соответствие деятельности организации')),
                ('question', models.TextField(null=True, verbose_name='Вопрос')),
                ('multiple_answer', models.BooleanField(verbose_name='Множественный ответ')),
                ('business_process', models.CharField(blank=True, choices=[('M', 'Управления'), ('B', 'Основные'), ('A', 'Вспомогательные')], max_length=20, null=True, verbose_name='Вид бизнес-процесса')),
            ],
            options={
                'verbose_name': 'Показатель - степень',
                'verbose_name_plural': 'Показатели - степень',
            },
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500, verbose_name='Ответ')),
                ('choise', models.BooleanField(blank=True, default=False, null=True, verbose_name='Выбор')),
                ('value', models.SmallIntegerField(verbose_name='Значения для расчета')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.degree', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
            },
        ),
    ]
