# Generated by Django 3.1 on 2020-09-07 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование частного показателя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('question', models.TextField(blank=True, verbose_name='Вопрос')),
                ('multiple_answer', models.BooleanField(verbose_name='Предпологает множественный ответ')),
                ('indicator_of_share', models.BooleanField(verbose_name='Показатель доля')),
            ],
            options={
                'verbose_name': 'Частный показатель',
                'verbose_name_plural': 'Частные показатели',
            },
        ),
        migrations.CreateModel(
            name='AnswerInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.TextField(verbose_name='Вопрос для для определения доли')),
                ('total_quantity', models.TextField(verbose_name='Вопрос для определения общего количества')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.degree', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Рассчетные значения для показателя - доля',
                'verbose_name_plural': 'Рассчетные значения для показателя - доля',
            },
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('value', models.FloatField(verbose_name='Значения для расчета')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.degree', verbose_name='Показатель')),
            ],
            options={
                'verbose_name': 'Вариант ответа для показателя - степень',
                'verbose_name_plural': 'Варианты ответа для показателя - степень',
            },
        ),
    ]
