# Generated by Django 3.1 on 2020-10-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerinput',
            name='quantity',
            field=models.TextField(verbose_name='Вопрос для определения доли'),
        ),
    ]
