# Generated by Django 3.1 on 2020-09-06 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerchoice',
            options={'verbose_name': 'Вариант ответа для показателя - степень', 'verbose_name_plural': 'Варианты ответа для показателя - степень'},
        ),
        migrations.AlterModelOptions(
            name='answerinput',
            options={'verbose_name': 'Рассчетные значения для показателя - доля', 'verbose_name_plural': 'Рассчетные значения для показателя - доля'},
        ),
        migrations.AlterModelOptions(
            name='degree',
            options={'verbose_name': 'Частный показатель', 'verbose_name_plural': 'Частные показатели'},
        ),
        migrations.RemoveField(
            model_name='answerchoice',
            name='choise',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='applying',
        ),
        migrations.AlterField(
            model_name='answerchoice',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answerchoice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.degree', verbose_name='Показатель'),
        ),
        migrations.AlterField(
            model_name='answerinput',
            name='quantity',
            field=models.TextField(verbose_name='Вопрос для для определения доли'),
        ),
        migrations.AlterField(
            model_name='answerinput',
            name='total_quantity',
            field=models.TextField(verbose_name='Вопрос для определения общего количества'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='indicator_of_share',
            field=models.BooleanField(verbose_name='Показатель доля'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='multiple_answer',
            field=models.BooleanField(verbose_name='Предпологает множественный ответ'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.TextField(verbose_name='Наименование частного показателя'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='question',
            field=models.TextField(blank=True, verbose_name='Вопрос'),
        ),
    ]
