# Generated by Django 3.1 on 2020-10-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_industry_degree'),
        ('indicators', '0002_auto_20201009_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='industry',
            field=models.ManyToManyField(to='account.Industry'),
        ),
    ]
